version: "3.9"

services:
  database:
    container_name: book_reviewer_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: book_reviewer
    ports:
      - "5432:5432"
  keycloak:
    container_name: book_reviewer_identity
    image: keycloak/keycloak:20.0.3
    command:
      - "start-dev --http-relative-path /auth --import-realm --auto-build"
    environment:
      KEYCLOAK_DB: dev-file
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KEYCLOAK_FEATURES: scripts
    volumes:
      - type: bind
        source: ./tmp
        target: /opt/keycloak/data/import
        read_only: true
    ports:
      - "8888:8080"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: book_reviewer_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      #     interval at which zookeeper will send heart beat
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: book_reviewer_broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

