version: "3.9"

services:
  database:
    image: postgres:15.1
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: book_review
    ports:
      - "5432:5432"
  keycloak:
    image: keycloak/keycloak:20.0.3
    command:
      - "start-dev --http-relative-path /auth --import-realm --auto-build"
    environment:
      KEYCLOAK_DB: dev-file
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KEYCLOAK_FEATURES: scripts
    volumes:
      - type: bind
        source: ./tmp
        target: /opt/keycloak/data/import
        read_only: true
    ports:
      - "8888:8080"
  sqs:
    image: softwaremill/elasticmq-native
    volumes:
      - type: bind
        source: ./tmp/sqs-queue-definition.conf
        target: /opt/elasticmq.conf
        read_only: true
    ports:
      - "9324:9324"
      - "9325:9325"

