spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_reviewer
    password: test
    username: test
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/spring
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
  devtools:
    livereload:
      enabled: true
clients:
  open-library:
    base-url: https://openlibrary.org
messaging:
  kafka:
    bootstrap-servers: localhost:9092
